export const movieslist = [
  {
    adult: false,
    backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    genre_ids: [28, 35, 878],
    id: 533535,
    original_language: "en",
    original_title: "Deadpool & Wolverine",
    overview:
      "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    popularity: 6334.004,
    poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    release_date: "2024-07-24",
    title: "Deadpool & Wolverine",
    video: false,
    vote_average: 7.763,
    vote_count: 2159,
  },
  {
    adult: false,
    backdrop_path: "/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg",
    genre_ids: [16, 10751, 12, 35],
    id: 1022789,
    original_language: "en",
    original_title: "Inside Out 2",
    overview:
      "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
    popularity: 3413.374,
    poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    release_date: "2024-06-11",
    title: "Inside Out 2",
    video: false,
    vote_average: 7.6,
    vote_count: 2675,
  },
  {
    adult: false,
    backdrop_path: "/58D6ZAvOKxlHjyX9S8qNKSBE9Y.jpg",
    genre_ids: [28, 12, 18, 53],
    id: 718821,
    original_language: "en",
    original_title: "Twisters",
    overview:
      "As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
    popularity: 2373.617,
    poster_path: "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
    release_date: "2024-07-10",
    title: "Twisters",
    video: false,
    vote_average: 7.065,
    vote_count: 942,
  },
  {
    adult: false,
    backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
    genre_ids: [16, 10751, 35, 28],
    id: 519182,
    original_language: "en",
    original_title: "Despicable Me 4",
    overview:
      "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
    popularity: 2163.327,
    poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
    release_date: "2024-06-20",
    title: "Despicable Me 4",
    video: false,
    vote_average: 7.3,
    vote_count: 1145,
  },
  {
    adult: false,
    backdrop_path: "/3q01ACG0MWm0DekhvkPFCXyPZSu.jpg",
    genre_ids: [28, 80, 53, 35],
    id: 573435,
    original_language: "en",
    original_title: "Bad Boys: Ride or Die",
    overview:
      "After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
    popularity: 1840.966,
    poster_path: "/oGythE98MYleE6mZlGs5oBGkux1.jpg",
    release_date: "2024-06-05",
    title: "Bad Boys: Ride or Die",
    video: false,
    vote_average: 7.602,
    vote_count: 1637,
  },
  {
    adult: false,
    backdrop_path: "/okVLmXL5y18dfN2R4ufMZEGaeCd.jpg",
    genre_ids: [28, 80],
    id: 1160018,
    original_language: "hi",
    original_title: "Kill",
    overview:
      "When an army commando finds out his true love is engaged against her will, he boards a New Dehli-bound train in a daring quest to derail the arranged marriage. But when a gang of knife-wielding thieves begin to terrorize innocent passengers on his train, the commando takes them on himself in a death-defying kill-spree to save those around him — turning what should have been a typical commute into an adrenaline-fueled thrill ride.",
    popularity: 1474.491,
    poster_path: "/m2zXTuNPkywdYLyWlVyJZW2QOJH.jpg",
    release_date: "2024-07-03",
    title: "Kill",
    video: false,
    vote_average: 7.019,
    vote_count: 77,
  },
  {
    adult: false,
    backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
    genre_ids: [27, 878],
    id: 945961,
    original_language: "en",
    original_title: "Alien: Romulus",
    overview:
      "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
    popularity: 1465.145,
    poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
    release_date: "2024-08-13",
    title: "Alien: Romulus",
    video: false,
    vote_average: 7.2,
    vote_count: 454,
  },
  {
    adult: false,
    backdrop_path: "/9BQqngPfwpeAfK7c2H3cwIFWIVR.jpg",
    genre_ids: [10749, 18],
    id: 1079091,
    original_language: "en",
    original_title: "It Ends with Us",
    overview:
      "Lily Bloom overcomes a traumatic childhood to embark on a new life in Boston and chase a lifelong dream of opening her own business. A chance meeting with charming neurosurgeon Ryle Kincaid sparks an intense connection, but as the two fall deeply in love, Lily begins to see sides of Ryle that remind her of her parents' relationship.",
    popularity: 1345.038,
    poster_path: "/AjV6jFJ2YFIluYo4GQf13AA1tqu.jpg",
    release_date: "2024-08-07",
    title: "It Ends with Us",
    video: false,
    vote_average: 7.04,
    vote_count: 126,
  },
  {
    adult: false,
    backdrop_path: "/z1aZkp16kzguKi3BHKCuRGRNGq4.jpg",
    genre_ids: [27, 878, 53],
    id: 762441,
    original_language: "en",
    original_title: "A Quiet Place: Day One",
    overview:
      "As New York City is invaded by alien creatures who hunt by sound, a woman named Sam fights to survive with her cat.",
    popularity: 1168.62,
    poster_path: "/hU42CRk14JuPEdqZG3AWmagiPAP.jpg",
    release_date: "2024-06-26",
    title: "A Quiet Place: Day One",
    video: false,
    vote_average: 6.9,
    vote_count: 1403,
  },
  {
    adult: false,
    backdrop_path: "/2MJIfQDA9orY3uVSnzExogbdhH6.jpg",
    genre_ids: [16, 35, 12, 10751],
    id: 831815,
    original_language: "en",
    original_title: "Saving Bikini Bottom: The Sandy Cheeks Movie",
    overview:
      "When Bikini Bottom is scooped from the ocean, scientific squirrel Sandy Cheeks and her pal SpongeBob SquarePants saddle up for Texas to save their town.",
    popularity: 1162.94,
    poster_path: "/30YnfZdMNIV7noWLdvmcJS0cbnQ.jpg",
    release_date: "2024-08-01",
    title: "Saving Bikini Bottom: The Sandy Cheeks Movie",
    video: false,
    vote_average: 6.426,
    vote_count: 157,
  },
  {
    adult: false,
    backdrop_path: "/h9YlRHAZWOWtGonllmj6JJg1FrE.jpg",
    genre_ids: [28, 12, 16, 10751, 14],
    id: 588648,
    original_language: "zh",
    original_title: "Dragonkeeper",
    overview:
      "Set in Han Imperial China, the plot follows the adventures of enslaved girl Ping with ancient dragon Long Danzi. Dragons had been banished from the kingdom. Ping, an orphan, finds one of the last remaining dragon eggs. Palace guards force Ping to run away in order to return the dragon egg to the ocean and save all dragons from extinction. Ping discovers that she is a true Dragonkeeper.",
    popularity: 1107.796,
    poster_path: "/ggZGnJLzO3BTu7ysuuIzou3Oex5.jpg",
    release_date: "2024-04-11",
    title: "Dragonkeeper",
    video: false,
    vote_average: 7.338,
    vote_count: 40,
  },
  {
    adult: false,
    backdrop_path: "/aswBReNN2adqTiOBnvh96RCDeJP.jpg",
    genre_ids: [28, 80, 18],
    id: 959092,
    original_language: "fr",
    original_title: "Farang",
    overview:
      "Sam is a professional boxer about to get released from prison. While on parole, his past catches up with him and he has no choice but to flee. Five years later, he has rebuilt a simple life on an exotic island in Thailand with his wife and her daughter, but when he gets blackmailed by a dangerous local godfather, he must embark on a dangerous drug smuggling mission which results in a tragedy. Now has only one purpose: to seek merciless vengeance.",
    popularity: 1046.802,
    poster_path: "/u9035lysUz3ccloQt0SeIp1Mu8a.jpg",
    release_date: "2023-06-28",
    title: "Mayhem!",
    video: false,
    vote_average: 6.734,
    vote_count: 126,
  },
  {
    adult: false,
    backdrop_path: "/y6Z8aogJjuAk9rWVIl1xpV5GENt.jpg",
    genre_ids: [28, 53],
    id: 1129598,
    original_language: "en",
    original_title: "Prey",
    overview:
      "A young couple is compelled to leave their Christian missionary station in the Kalahari Desert after being threatened with death by an extremist militant gang. After crashing their aircraft they must battle man and beast for their lives.",
    popularity: 1056.115,
    poster_path: "/5wAlO5zZ3IyzLBAf7cp5WejalmG.jpg",
    release_date: "2024-03-15",
    title: "Prey",
    video: false,
    vote_average: 6.508,
    vote_count: 177,
  },
  {
    adult: false,
    backdrop_path: "/QflfyU07MiQXSqTUCmG9Xfq0Ws.jpg",
    genre_ids: [28, 18, 10749],
    id: 1281826,
    original_language: "en",
    original_title: "One Fast Move",
    overview:
      "A dishonorably discharged soldier seeks out his estranged father to help him pursue his dream of becoming a professional motorcycle racer. While training, he meets a small-town, aspiring singer and a motorcycle shop owner who begin to break down the walls his father’s absence had built up.",
    popularity: 929.525,
    poster_path: "/hdBUjfbdr1ymS0kycAT7qguOmWA.jpg",
    release_date: "2024-08-07",
    title: "One Fast Move",
    video: false,
    vote_average: 6.814,
    vote_count: 86,
  },
  {
    adult: false,
    backdrop_path: "/1wP1phHo2CROOqzv7Azs0MT5esU.jpg",
    genre_ids: [16, 35, 10751, 12, 28],
    id: 748783,
    original_language: "en",
    original_title: "The Garfield Movie",
    overview:
      "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
    popularity: 901.565,
    poster_path: "/xYduFGuch9OwbCOEUiamml18ZoB.jpg",
    release_date: "2024-04-30",
    title: "The Garfield Movie",
    video: false,
    vote_average: 7.2,
    vote_count: 795,
  },
  {
    adult: false,
    backdrop_path: "/qQqEq11QsXdSTmYs3M7D5bxFHJg.jpg",
    genre_ids: [28, 35, 80],
    id: 1059064,
    original_language: "en",
    original_title: "The Instigators",
    overview:
      "Rory and Cobby are unlikely partners thrown together for a heist. But when it goes awry, they team up to outrun police, backward bureaucrats, and a vengeful crime boss.",
    popularity: 891.661,
    poster_path: "/thI9pM7Qu43f42sOOl5wy75UAo.jpg",
    release_date: "2024-08-02",
    title: "The Instigators",
    video: false,
    vote_average: 6.4,
    vote_count: 200,
  },
  {
    adult: false,
    backdrop_path: "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
    genre_ids: [878, 12, 28],
    id: 653346,
    original_language: "en",
    original_title: "Kingdom of the Planet of the Apes",
    overview:
      "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
    popularity: 852.588,
    poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
    release_date: "2024-05-08",
    title: "Kingdom of the Planet of the Apes",
    video: false,
    vote_average: 7.171,
    vote_count: 2569,
  },
  {
    adult: false,
    backdrop_path: "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
    genre_ids: [28, 12, 878],
    id: 786892,
    original_language: "en",
    original_title: "Furiosa: A Mad Max Saga",
    overview:
      "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.",
    popularity: 772.741,
    poster_path: "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
    release_date: "2024-05-22",
    title: "Furiosa: A Mad Max Saga",
    video: false,
    vote_average: 7.605,
    vote_count: 2751,
  },
  {
    adult: false,
    backdrop_path: "/tqSg1hHiSWhHAhnjDhhevaFGsP0.jpg",
    genre_ids: [28, 18],
    id: 1066262,
    original_language: "en",
    original_title: "The Convert",
    overview:
      "Munro, a soldier turned lay preacher, comes to New Zealand to minister to the first British colonists, but he is converted by the powerful chief Maianui to serve a different purpose.",
    popularity: 700.447,
    poster_path: "/e5ZqqPlhKstzB4geibpZh38w7Pq.jpg",
    release_date: "2024-03-14",
    title: "The Convert",
    video: false,
    vote_average: 6.255,
    vote_count: 47,
  },
  {
    adult: false,
    backdrop_path: "/lyEuje8cKjbWliYUGrOaoHVmc1R.jpg",
    genre_ids: [28, 35, 12],
    id: 1002088,
    original_language: "ko",
    original_title: "크로스",
    overview:
      "In the ultimate test of marriage, an agent-turned-househusband gets tangled in a perilous mission with his detective wife, who's clueless about his past.",
    popularity: 727.759,
    poster_path: "/aE9WqOApdRYsowsGE0118dyA4c9.jpg",
    release_date: "2024-08-05",
    title: "Mission: Cross",
    video: false,
    vote_average: 7.093,
    vote_count: 54,
  },
];
